
CREATE TABLE STUDENT (
    STUDENT_NO INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(50),
    STUDENT_DOB DATE,
    STUDENT_DOJ DATE
);

insert into STUDENT(STUDENT_NO , STUDENT_NAME,STUDENT_DOB ,STUDENT_DOJ)
values(1,'John Doe','2000-01-01',GETDATE());

